# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application - Ubuntu

on:
  push:
    branches: [tt-*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: BjornLuG/substitute-string-action@v1
        id: inject_version
        with:
          _input-file: "./tfe.py"
          _output-file: "./tfe.py"
          _format-key: "%%version%%"
          version: "v0.0.0 branch ${{ github.base_ref }} (${{ github.sha }})"
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: build with pyinstaller
        run: |
          pyinstaller --onefile tfe.py
      - name: Copy to Release
        run: |
          mkdir -p ./release/ubuntu
          cp ./dist/tfe ./release/ubuntu/tfe
      - name: Commit onefile binary from PyInstaller
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Tom Straub
          author_email: tstraub@hashicorp.com
          message: "PyInstaller --onefile Binary Auto-Commit"
          add: "./release/ubuntu/tfe"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
